when:
  - event: tag
    branch: main

steps:
  - name: build-icons
    image: alpine
    commands:
      - apk add just
      - just alpine-install-deps
      - just build-icons
  - name: archive-icons
    image: alpine
    commands:
      - apk add tar
      - tar czf icons.tar.gz --directory=build icons
  - name: godot-build-linux
    image: "barichello/godot-ci"
    commands:
      - mkdir -v -p godot-build
      - godot -v --export-release "Linux/X11" godot-build/Find\ Billy\ for\ Linux\ ${CI_COMMIT_TAG}.x86_64 --headless
      - ls godot-build
  - name: godot-build-windows
    image: "barichello/godot-ci"
    commands:
      - mkdir -v -p godot-build
      - godot -v --export-release "Windows Desktop" godot-build/Find\ Billy\ for\ Windows\ ${CI_COMMIT_TAG}.exe --headless
      - ls godot-build
  - name: godot-build-mac
    image: "barichello/godot-ci"
    commands:
      - mkdir -v -p godot-build
      - godot -v --export-release "macOS" godot-build/Find\ Billy\ for\ macOS\ ${CI_COMMIT_TAG}.zip --headless
      - ls godot-build
  - name: godot-build-web
    image: "barichello/godot-ci"
    commands:
      - mkdir -v -p godot-build/Find\ Billy\ for\ Web\ ${CI_COMMIT_TAG}
      - godot -v --export-release "Web" godot-build/Find\ Billy\ for\ Web\ ${CI_COMMIT_TAG}/index.html --headless
      - zip godot-build/Find\ Billy\ for\ Web\ ${CI_COMMIT_TAG}.zip godot-build/Find\ Billy\ for\ Web\ ${CI_COMMIT_TAG}/*
      - rm -rf godot-build/Find\ Billy\ for\ Web\ ${CI_COMMIT_TAG}
      - ls godot-build
  - name: godot-build-linux-pack
    image: "barichello/godot-ci"
    commands:
      - mkdir -v -p godot-build
      - godot -v --export-pack "Linux/X11" godot-build/godot-runner.pck --headless
      - ls godot-build
  - name: gitea-release
    image: woodpeckerci/plugin-release
    settings:
      GITEA_TOKEN:
        from_secret: gitea_token
      api_key:
        from_secret: GITEA_TOKEN
      base_url: "https://codeberg.org"
      files:
        - godot-build/*
        - icons.tar.gz
      checksum:
        - sha256
        - sha512
      title: "${CI_COMMIT_TAG}"
      note: ${CI_REPO_LINK}/src/branch/main/CHANGELOG.md#${CI_COMMIT_TAG/\./-}
      path:
        exclude: [ '*.md', '.chglog/**' ]
