when:
  - event: tag
    branch: main

steps:
  - name: build-icons
    image: alpine
    commands:
      - apk add just
      - just alpine-install-deps
      - just build-icons
  - name: archive-icons
    image: alpine
    commands:
      - apk add tar
      - tar czf icons.tar.gz --directory=build icons
  - name: godot-build-linux
    image: "barichello/godot-ci"
    commands:
      - mkdir -v -p godot-build
      - godot -v --export-release "linux_x86-64" godot-build/Find-Billy_v${CI_COMMIT_TAG}_linux_x86-64 --headless
      - ls godot-build
  - name: godot-build-windows
    image: "barichello/godot-ci"
    commands:
      - mkdir -v -p godot-build
      - godot -v --export-release "windows_x86-64" godot-build/Find-Billy_v${CI_COMMIT_TAG}_windows_x86-64.exe --headless
      - ls godot-build
  - name: godot-build-mac
    image: "barichello/godot-ci"
    commands:
      - mkdir -v -p godot-build
      - godot -v --export-release "macos_arm64" godot-build/Find-Billy_v${CI_COMMIT_TAG}_macos_arm64.zip --headless
      - ls godot-build
  - name: godot-build-web
    image: "barichello/godot-ci"
    commands:
      - mkdir -v -p godot-build/Find-Billy_Web\ ${CI_COMMIT_TAG}
      - godot -v --export-release "web_wasm" godot-build/Find-Billy_v${CI_COMMIT_TAG}_web_wasm/index.html --headless
      - zip godot-build/Find-Billy_v${CI_COMMIT_TAG}_web_wasm.zip godot-build/Find-Billy_v${CI_COMMIT_TAG}_web_wasm/*
      - rm -rf godot-build/Find-Billy_v${CI_COMMIT_TAG}_web_wasm
      - ls godot-build
  - name: godot-build-linux-pack
    image: "barichello/godot-ci"
    commands:
      - mkdir -v -p godot-build
      - godot -v --export-pack "linux_x86-64" godot-build/godot-runner.pck --headless
      - ls godot-build
  - name: gitea-release
    image: woodpeckerci/plugin-release
    settings:
      GITEA_TOKEN:
        from_secret: gitea_token
      api_key:
        from_secret: GITEA_TOKEN
      base_url: "https://codeberg.org"
      files:
        - godot-build/*
        - icons.tar.gz
      checksum:
        - sha256
        - sha512
      title: "${CI_COMMIT_TAG}"
      note: ${CI_REPO_LINK}/src/branch/main/CHANGELOG.md#${CI_COMMIT_TAG/\./-}
      path:
        exclude: [ '*.md', '.chglog/**' ]
