pipeline:
  godot-build-linux:
    image: barichello/godot-ci
    commands:
      - mkdir -v -p godot-build
      - godot -v --export "Linux/X11" godot-build/Find\ Billy\ for\ Linux\ ${CI_COMMIT_TAG}.x86_64
      - ls godot-build
    when:
      event: tag
  godot-build-windows:
    image: barichello/godot-ci
    commands:
      - mkdir -v -p godot-build
      - godot -v --export "Windows Desktop" godot-build/Find\ Billy\ for\ Windows\ ${CI_COMMIT_TAG}.exe
      - ls godot-build
    when:
      event: tag
  godot-build-mac:
    image: barichello/godot-ci
    commands:
      - mkdir -v -p godot-build
      - godot -v --export "Mac OSX" godot-build/Find\ Billy\ for\ Mac\ OSX\ ${CI_COMMIT_TAG}.zip
      - ls godot-build
    when:
      event: tag
  godot-build-web:
    image: barichello/godot-ci
    commands:
      - mkdir -v -p godot-build/Find\ Billy\ for\ Web\ ${CI_COMMIT_TAG}
      - godot -v --export "HTML5" godot-build/Find\ Billy\ for\ Web\ ${CI_COMMIT_TAG}/index.html
      - zip godot-build/Find\ Billy\ for\ Web\ ${CI_COMMIT_TAG}.zip godot-build/Find\ Billy\ for\ Web\ ${CI_COMMIT_TAG}/*
      - rm -rf godot-build/Find\ Billy\ for\ Web\ ${CI_COMMIT_TAG}
      - ls godot-build
    when:
      event: tag
  godot-build-linux-pack:
    image: barichello/godot-ci
    commands:
      - mkdir -v -p godot-build
      - godot -v --export-pack "Linux/X11" godot-build/godot-runner.pck
      - ls godot-build
    when:
      event: tag
