when:
  - event: tag
    branch: main

steps:
  - name: archive-icons
    image: alpine
    commands:
      - apk add just imagemagick inkscape
      - just archive-icons
  - name: godot-build
    image: "barichello/godot-ci"
    commands:
      - apk add just
      - just --set godot_exe godot --set zip_exe zip godot-build --set version ${CI_COMMIT_TAG}
  - name: gitea-release
    image: woodpeckerci/plugin-release
    settings:
      GITEA_TOKEN:
        from_secret: gitea_token
      api_key:
        from_secret: GITEA_TOKEN
      base_url: "https://codeberg.org"
      files:
        - godot-build/*
        - icons.tar.gz
      checksum:
        - sha256
        - sha512
      title: "${CI_COMMIT_TAG}"
      note: ${CI_REPO_LINK}/src/branch/main/CHANGELOG.md#${CI_COMMIT_TAG/\./-}
      path:
        exclude: [ '*.md', '.chglog/**' ]
